name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up job
        run: echo "Iniciando build crDroid para Galaxy A55"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            git-core gnupg flex bison build-essential zip curl zstd \
            libncurses5-dev libncursesw5-dev libssl-dev \
            libxml2 libxml2-utils xsltproc unzip fontconfig \
            openjdk-17-jdk openjdk-17-jdk-headless \
            libc6-i386 lib32ncurses-dev lib32z1 \
            liblz4-tool libtinfo5

      - name: Instalar repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Inicializar repo crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          git clone --depth=1 https://github.com/TrebleDroid/manifest.git .repo/manifests
          repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1

      - name: Sincronizar repositório (repo sync)
        run: |
          cd ~/crdroid
          repo sync -c -j2 --no-tags --no-clone-bundle | tee repo_sync.log

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar repositório sincronizado
        run: |
          cd ~
          tar -I zstd -cf repo.tar.zst crdroid

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: crdroid_repo_sync
          path: ~/repo.tar.zst
