name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Instalar dependências básicas
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
          git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev \
          lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libncurses5-dev:i386 \
          libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
          rsync schedtool squashfs-tools xsltproc zip zlib1g-dev unzip

    - name: Instalar repo tool
      run: |
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo > /usr/bin/repo
        sudo chmod a+rx /usr/bin/repo

    - name: Inicializar repo crDroid Android 15
      run: |
        mkdir -p ~/crdroid
        cd ~/crdroid
        repo init -u https://github.com/TrebleDroid/treble_manifest.git -b android-15 --depth=1

    - name: Sincronizar repositório (repo sync)
      run: |
        cd ~/crdroid
        repo sync -c -j2 --no-tags --no-clone-bundle

    - name: Compactar repositório sincronizado
      run: |
        cd ~
        tar -I 'zstd -T0' -cf repo.tar.zst crdroid/.repo

    - name: Fazer upload do .repo.tar.zst
      uses: actions/upload-artifact@v4
      with:
        name: repo-cache
        path: ~/repo.tar.zst
