jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Preparar ambiente
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y \
          bc bison build-essential curl flex git gnupg gperf \
          libncurses5 libncurses5:i386 libssl-dev libxml2 libxml2-utils \
          lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev \
          liblz4-tool libncursesw5 lib32ncurses5 lib32z1 lib32stdc++6 \
          libtinfo5 libtinfo5:i386 openjdk-17-jdk-headless

    - name: Instalar ferramenta de reposit贸rio
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Inicializar reposit贸rio crDroid Android 15
      run: |
        mkdir -p ~/crdroid
        cd ~/crdroid
        ~/bin/repo init -u https://github.com/TrebleDroid/manifest.git -b td-aosp-15.0 --depth=1 --no-tags

    - name: Sincronizar reposit贸rio (repo sync)
      run: |
        cd ~/crdroid
        ~/bin/repo sync -c -j2 --no-tags --no-clone-bundle

    - name: Compactar reposit贸rio sincronizado
      run: |
        cd ~
        tar --zstd -cf repo.tar.zst crdroid

    - name: Fazer upload do .repo.tar.zst
      uses: actions/upload-artifact@v4
      with:
        name: repo-crdroid-td15
        path: ~/repo.tar.zst
