Arquivo: .github/workflows/build.yml

name: Construir crDroid Android 15

on: workflow_dispatch:

jobs: build: name: Construir ROM crDroid runs-on: ubuntu-latest

steps:
  - name: Preparar ambiente
    run: |
      sudo apt-get update
      sudo apt-get install -y \
        git-core gnupg flex bison build-essential zip curl zlib1g-dev \
        gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses-dev \
        x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils \
        xsltproc unzip bc python3 python3-pip openjdk-17-jdk \
        libssl-dev repo liblz4-tool libncursesw6 libtinfo6

  - name: Instalar ferramenta de repositório
    run: |
      mkdir -p ~/bin
      curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
      chmod a+x ~/bin/repo

  - name: Inicializar repositório crDroid Android 15
    run: |
      mkdir -p ~/crdroid
      cd ~/crdroid
      repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1 --no-repo-verify

  - name: Sincronizar repositório (repo sync)
    run: |
      cd ~/crdroid
      repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j8

  - name: Compactar repositório sincronizado
    run: |
      cd ~
      tar --zstd -cf repo.tar.zst crdroid

  - name: Fazer upload do .repo.tar.zst
    uses: actions/upload-artifact@v4
    with:
      name: repo.tar.zst
      path: ~/repo.tar.zst

  - name: Pós-checkout
    run: |
      git version
      git config --global --add safe.directory "$GITHUB_WORKSPACE"
      git config --global --unset-all http.https://github.com/.extraheader || true

