name: Preparar Ambiente crDroid A55

on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest

    steps:
    - name: Instalar dependências básicas
      run: |
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib \
        git gnupg gperf imagemagick libncurses5-dev libncurses5-dev:i386 libreadline-dev \
        libssl-dev liblz4-tool libxml2 libxml2-utils lzop pngcrush rsync schedtool \
        squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk python3 python3-pip \
        tar zstd

    - name: Instalar repo tool
      run: |
        mkdir -p ~/bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
        chmod a+x ~/bin/repo
        echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

    - name: Inicializar repo crDroid Android 15
      run: |
        mkdir -p ~/crdroid
        cd ~/crdroid
        ~/bin/repo init -u https://github.com/crdroidandroid/android.git -b 15.0

    - name: Sincronizar repositório (repo sync)
      run: |
        cd ~/crdroid
        ~/bin/repo sync -c --no-tags --no-clone-bundle --force-sync --optimized-fetch --prune -j4 --depth=1

    - name: Compactar repositório sincronizado
      run: |
        cd ~
        tar --zstd -cf repo.tar.zst crdroid/.repo

    - name: Fazer upload do .repo.tar.zst
      uses: actions/upload-artifact@v4
      with:
        name: repo-crdroid-15
        path: ~/repo.tar.zst
