name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up job
        run: echo "Iniciando build do crDroid Android 15 para Galaxy A55"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            bc bison build-essential curl flex git gnupg gperf \
            libssl-dev libxml2 libxml2-utils lzop pngcrush rsync \
            schedtool squashfs-tools xsltproc zip zlib1g-dev \
            liblz4-tool lib32z1 lib32ncurses-dev lib32readline-dev lib32z1-dev \
            gcc g++ python-is-python3 curl wget unzip \
            openjdk-17-jdk-headless openjdk-17-jre-headless \
            libncurses-dev libncursesw6 libncursesw6:i386 libtinfo6 libtinfo6:i386

      - name: Instalar repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo "$HOME/bin" >> $GITHUB_PATH

      - name: Inicializar repo crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1 --no-tags

      - name: Sincronizar repositório (repo sync)
        run: |
          cd ~/crdroid
          repo sync -c -j2 --no-tags --no-clone-bundle | tee repo_sync.log

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar repositório sincronizado
        run: |
          cd ~
          tar --zstd -cf repo.tar.zst crdroid/.repo

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: repo_cache
          path: ~/repo.tar.zst
