name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Preparar ambiente
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y git-core gnupg flex bison build-essential \
          zip curl zlib1g-dev:i386 libc6-dev:i386 libncurses5:i386 \
          libstdc++6:i386 lib32z1-dev libbz2-1.0:i386 libssl-dev \
          liblz4-tool libxml2-utils rsync ca-certificates \
          python3 python-is-python3 openjdk-17-jdk bc \
          libncurses5-dev:i386 libncurses-dev:i386 \
          lib32ncurses6 lib32z1 libgl1-mesa-dev unzip \
          squashfs-tools xsltproc zip zstd

    - name: Instalar repo tool
      run: |
        sudo curl https://storage.googleapis.com/git-repo-downloads/repo -o /usr/local/bin/repo
        sudo chmod +x /usr/local/bin/repo

    - name: Inicializar repo crDroid Android 15
      run: |
        mkdir -p ~/crdroid
        cd ~/crdroid
        repo init -u https://github.com/crdroidandroid/android.git -b 15.0 --depth=1

    - name: Sincronizar repositório (repo sync)
      run: |
        cd ~/crdroid
        repo sync -c -j2 --no-tags --no-clone-bundle

    - name: Compactar repositório sincronizado
      run: |
        cd ~
        tar --zstd -cf repo.tar.zst crdroid

    - name: Fazer upload do .repo.tar.zst
      uses: actions/upload-artifact@v4
      with:
        name: crdroid-repo-backup
        path: ~/repo.tar.zst
