name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Liberar espaço extra
      run: |
        sudo rm -rf /usr/share/dotnet /opt/ghc /usr/local/lib/android /opt/hostedtoolcache

    - name: Preparar ambiente
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y bc bison build-essential curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick libncurses5-dev libncurses5-dev:i386 libreadline-dev libssl-dev liblz4-tool libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev openjdk-17-jdk python3 python3-pip
        sudo apt install -y repo

    - name: Init repo
      run: |
        mkdir -p ~/crdroid
        cd ~/crdroid
        repo init -u https://github.com/crdroidandroid/android.git -b 15.0
        repo sync -c --no-tags --no-clone-bundle --force-sync --optimized-fetch --prune -j4 --depth=1

    - name: Clonar device, vendor, kernel sources
      run: |
        cd ~/crdroid
        git clone https://github.com/krexdall/device_samsung_a55 device/samsung/a55
        git clone https://github.com/krexdall/vendor_samsung_a55 vendor/samsung/a55
        git clone https://github.com/krexdall/kernel_samsung_a55 kernel/samsung/a55

    - name: Build ROM
      run: |
        cd ~/crdroid
        source build/envsetup.sh
        lunch a55-userdebug
        mka bacon -j$(nproc --all)

    - name: Upload ROM
      uses: actions/upload-artifact@v4
      with:
        name: crDroid-A55
        path: ~/crdroid/out/target/product/*/*.zip
