name: Construir crDroid A55 Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build

    steps:
      - name: Set up job
        run: echo "Iniciando job de build"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y \
            git-core gnupg flex bison build-essential zip curl zstd \
            libncurses5-dev libncursesw5-dev libssl-dev \
            libxml2 libxml2-utils xsltproc unzip fontconfig \
            openjdk-17-jdk openjdk-17-jdk-headless \
            libc6-i386 lib32ncurses-dev lib32z1 \
            liblz4-tool libtinfo6

      - name: Instalar repo tool
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+rx ~/bin/repo

      - name: Inicializar repo crDroid Android 15
        env:
          GIT_CONFIG_NOSYSTEM: 1
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          repo init -u https://github.com/TrebleDroid/manifest.git -b td-android-15.0 --depth=1

      - name: Sincronizar repositório (repo sync)
        run: |
          cd ~/crdroid
          repo sync -c -j2 --no-tags --no-clone-bundle

      - name: Compactar repositório sincronizado
        run: |
          cd ~
          tar -I 'zstd -19' -cf repo.tar.zst crdroid

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: repo-crdroid-td15
          path: ~/repo.tar.zst

      - name: Post Checkout
        run: |
          echo "Job finalizado"
