name: Construir crDroid Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev \
            lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush \
            rsync schedtool squashfs-tools xsltproc zip zlib1g-dev libtinfo5 libncurses5:i386 libtinfo5:i386 libtinfo-dev libtinfo5-dev \
            libncursesw5-dev libncursesw5:i386 libncurses5-dev:i386 git openjdk-17-jdk-headless python-is-python3 python3-pip wget

      - name: Instalar ferramenta de repositório
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Inicializar repositório crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          ~/bin/repo init -u https://github.com/tdroidd/treble_manifest.git -b 15 --depth=1

      - name: Sincronizar repositório (repo sync)
        run: |
          cd ~/crdroid
          ~/bin/repo sync -c --no-clone-bundle --no-tags --force-sync -j$(nproc --all)

      - name: Compactar repositório sincronizado
        run: |
          cd ~
          tar --exclude='*.git*' -cf repo.tar ~/crdroid
          zstd -T0 repo.tar

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: repo-crdroid-android15
          path: ~/repo.tar.zst

      - name: Pós-checkout
        run: |
          git version
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
