name: Construir crDroid Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y git aria2 python3 unzip zip bc curl gcc clang build-essential \
            libncurses5 libncurses5-dev libncurses5:i386 libncurses5-dev:i386 \
            libtinfo5 libtinfo5-dev libtinfo5:i386 libtinfo5-dev:i386 \
            libssl-dev liblz4-tool libncursesw5:i386 \
            lib32ncurses5-dev lib32z1 lib32stdc++6

      - name: Instalar ferramenta de reposit贸rio
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Inicializar reposit贸rio crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          ~/bin/repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1

      - name: Sincronizar reposit贸rio (repo sync)
        run: |
          cd ~/crdroid
          ~/bin/repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc) || true

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar reposit贸rio sincronizado
        run: |
          cd ~
          tar --exclude='.repo' -caf repo.tar.zst crdroid

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: crDroid_Source
          path: ~/repo.tar.zst
