name: Construir crDroid Android 15

on:
  workflow_dispatch:

jobs:
  build:
    name: Construir ROM crDroid
    runs-on: ubuntu-latest

    steps:
      - name: Preparar ambiente
        run: |
          sudo apt update
          sudo apt install -y \
            openjdk-17-jdk-headless \
            git-core \
            gnupg \
            flex \
            bison \
            build-essential \
            zip \
            curl \
            zlib1g-dev \
            gcc-multilib \
            g++-multilib \
            libc6-dev-i386 \
            libx11-dev \
            libgl1-mesa-dev \
            libxml2-utils \
            xsltproc \
            unzip \
            fontconfig \
            python-is-python3 \
            libncurses-dev \
            libtinfo-dev

      - name: Instalar ferramenta de reposit贸rio
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Inicializar reposit贸rio crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          ~/bin/repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1

      - name: Sincronizar reposit贸rio (repo sync)
        run: |
          cd ~/crdroid
          ~/bin/repo sync -c --force-sync --no-tags --no-clone-bundle -j$(nproc --all)

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar reposit贸rio sincronizado
        if: success()
        run: |
          cd ~
          tar --exclude='.repo' -cf repo.tar.zst -I 'zstd -19 -T0' crdroid

      - name: Fazer upload do .repo.tar.zst
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: repo_tarball
          path: ~/repo.tar.zst
