name: Build crDroid Android 15

on:
  workflow_dispatch:

jobs:
  build:
    name: Construir ROM crDroid
    runs-on: ubuntu-latest

    steps:
      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
          git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev \
          liblz4-tool libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools \
          xsltproc zip zlib1g-dev openjdk-17-jdk python-is-python3 libtinfo5-dev

      - name: Instalar ferramenta de reposit贸rio
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo
          echo 'export PATH=~/bin:$PATH' >> $GITHUB_ENV

      - name: Inicializar reposit贸rio crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          repo init -u https://github.com/TrebleDroid/manifest.git -b 15 --depth=1
        env:
          PATH: ${{ env.PATH }}

      - name: Sincronizar reposit贸rio (repo sync)
        run: |
          cd ~/crdroid
          repo sync -c --no-tags --no-clone-bundle -j8 || touch repo_sync_failed

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_failed_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar reposit贸rio sincronizado
        run: |
          cd ~
          tar -I zstd -cf repo.tar.zst crdroid

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: repo_crdroid_android15
          path: ~/repo.tar.zst
