name: Construir crDroid Android 15

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Preparar ambiente
        run: |
          sudo dpkg --add-architecture i386
          sudo sed -i 's|azure.archive.ubuntu.com|archive.ubuntu.com|g' /etc/apt/sources.list
          sudo apt update
          sudo apt install -y git aria2 python3 python3-pip openjdk-17-jdk \
              libncurses5 libncurses5-dev libncurses5:i386 \
              libtinfo5 libtinfo-dev libtinfo5:i386 libtinfo-dev:i386 \
              libssl-dev liblz4-tool

      - name: Instalar ferramenta de reposit贸rio
        run: |
          mkdir -p ~/bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

      - name: Inicializar reposit贸rio crDroid Android 15
        run: |
          mkdir -p ~/crdroid
          cd ~/crdroid
          ~/bin/repo init -u https://github.com/TrebleDroid/treble_manifest.git -b android-15.0 -m manifest.xml --depth=1

      - name: Sincronizar reposit贸rio (repo sync)
        run: |
          cd ~/crdroid
          ~/bin/repo sync -c --force-sync --no-clone-bundle --no-tags -j$(nproc --all)

      - name: Upload do log repo_sync.log se falhar
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: repo_sync_log
          path: ~/crdroid/repo_sync.log

      - name: Compactar reposit贸rio sincronizado
        run: |
          cd ~
          tar --exclude='.repo' -cvf repo.tar.zst crdroid

      - name: Fazer upload do .repo.tar.zst
        uses: actions/upload-artifact@v4
        with:
          name: repo_compactado
          path: ~/repo.tar.zst
